-- AlterTable
CREATE TYPE "ObjectAssetPurpose" AS ENUM ('MODEL', 'COMPONENT');

-- AlterTable
CREATE TYPE "ObjectAssetStatus" AS ENUM ('PROCESSING', 'READY', 'FAILED');

-- AlterTable
ALTER TABLE "ObjectAsset"
ADD COLUMN IF NOT EXISTS "format" TEXT,
ADD COLUMN IF NOT EXISTS "sizeBytes" INTEGER,
ADD COLUMN IF NOT EXISTS "purpose" "ObjectAssetPurpose" NOT NULL DEFAULT 'MODEL',
ADD COLUMN IF NOT EXISTS "status" "ObjectAssetStatus" NOT NULL DEFAULT 'READY',
ADD COLUMN IF NOT EXISTS "parsedMetadataUri" TEXT,
ADD COLUMN IF NOT EXISTS "parsedMetadataSha256" TEXT,
ADD COLUMN IF NOT EXISTS "metadataVersion" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "nodeCount" INTEGER,
ADD COLUMN IF NOT EXISTS "meshCount" INTEGER,
ADD COLUMN IF NOT EXISTS "materialCount" INTEGER,
ADD COLUMN IF NOT EXISTS "animationCount" INTEGER;
